SRCS_NAME=main.c\
		  zappy_client_getopt.c\
		  callback/callback.c\
		  callback/connect_nbr.c\
		  callback/inventaire.c\
		  callback/voir.c\
		  player/zappy_client_move.c\
		  player/zappy_player.c\
		  server_message/deplacement.c\
		  server_message/message.c\
		  server_message/mort.c\
		  tcp/zappy_client_receive.c\
		  tcp/zappy_client_transceive.c\
		  tcp/zappy_client.c\
