FROM debian:latest

RUN apt-get update -y \
	&& apt-get upgrade -y \
	&& apt-get install -y build-essential

EXPOSE 8080

ENV TERM "xterm-256color"

COPY . /zappy/

WORKDIR /zappy/server

RUN chmod +x /zappy/server/scripts/entrypoint.sh \
	&& make

CMD ["/zappy/server/scripts/entrypoint.sh"]
