SRCS_NAME=main.c\
		  error.c\
		  options.c\
		  free.c\
		  tick.c\
		  player/player.c\
		  player/move_commands.c\
		  player/commands.c\
		  player/see.c\
		  world/init.c\
		  world/resources.c
