SRCS_NAME=main.c\
		  error.c\
		  options.c\
		  free.c\
		  init.c\
		  tick.c\
		  tools.c\
		  update_commands.c\
		  graphical/update.c\
		  graphical/commands.c\
		  graphical/send_graphical_data.c\
		  graphical/tools.c\
		  player/broadcast.c\
		  player/commands.c\
		  player/fork.c\
		  player/move_commands.c\
		  player/player.c\
		  player/see.c\
		  tcp/auth.c\
		  tcp/init.c\
		  tcp/receipt.c\
		  tcp/response.c\
		  world/init.c\
		  world/resources.c
